# Step 1: Build the Angular application in a Node.js environment
FROM node:14 as build-step
WORKDIR /app
COPY package.json package-lock.json ./
RUN yarn install
COPY . .
RUN ng build --prod

# Step 2: Serve the application from Nginx
FROM nginx:1.19.0-alpine as prod-stage
COPY --from=build-step /app/dist/<your-app-name> /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]